<?php

use App\Http\Controllers\AdminDashboardController;
use App\Http\Controllers\AdminEditionContextController;
use App\Http\Controllers\AdminEventsController;
use App\Http\Controllers\AdminGalleriesController;
use App\Http\Controllers\AdminNewsController;
use App\Http\Controllers\AdminParticipantsController;
use App\Http\Controllers\AdminRequestAccessController;
use App\Http\Controllers\AdminSponsorsController;
use App\Http\Controllers\AdminUsersController;
use App\Http\Controllers\Auth\GoogleAuthenticationController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PublicPageController;
use App\Http\Middleware\EnsureAdminAccess;
use Illuminate\Support\Facades\Route;

Route::get('/', HomeController::class)->name('home');

Route::get('/admin/login', [GoogleAuthenticationController::class, 'showLogin'])->name('admin.login');
Route::get('/auth/google/redirect', [GoogleAuthenticationController::class, 'redirectToGoogle'])->name('auth.google.redirect');
Route::get('/auth/google/callback', [GoogleAuthenticationController::class, 'handleGoogleCallback'])->name('auth.google.callback');
Route::post('/logout', [GoogleAuthenticationController::class, 'logout'])->middleware('auth')->name('logout');
Route::get('/admin/request-access', AdminRequestAccessController::class)->middleware('auth')->name('admin.request-access');
Route::post('/admin/request-access', [AdminRequestAccessController::class, 'store'])->middleware('auth')->name('admin.request-access.store');
Route::post('/admin/context/edition', [AdminEditionContextController::class, 'store'])->middleware(EnsureAdminAccess::class)->name('admin.edition-context.store');
Route::get('/admin/users', [AdminUsersController::class, 'index'])->middleware(EnsureAdminAccess::class)->name('admin.users');
Route::post('/admin/users/access-requests/{accessRequest}/approve', [AdminUsersController::class, 'approve'])->middleware(EnsureAdminAccess::class)->name('admin.access-requests.approve');
Route::get('/admin/content/news', [AdminNewsController::class, 'index'])->middleware(EnsureAdminAccess::class)->name('admin.news.index');
Route::get('/admin/content/news/new', [AdminNewsController::class, 'create'])->middleware(EnsureAdminAccess::class)->name('admin.news.create');
Route::post('/admin/content/news', [AdminNewsController::class, 'store'])->middleware(EnsureAdminAccess::class)->name('admin.news.store');
Route::get('/admin/content/news/{id}', [AdminNewsController::class, 'edit'])->middleware(EnsureAdminAccess::class)->name('admin.news.edit');
Route::put('/admin/content/news/{id}', [AdminNewsController::class, 'update'])->middleware(EnsureAdminAccess::class)->name('admin.news.update');
Route::post('/admin/content/news/{id}/publish', [AdminNewsController::class, 'publish'])->middleware(EnsureAdminAccess::class)->name('admin.news.publish');
Route::post('/admin/content/news/{id}/unpublish', [AdminNewsController::class, 'unpublish'])->middleware(EnsureAdminAccess::class)->name('admin.news.unpublish');
Route::post('/admin/content/news/{id}/archive', [AdminNewsController::class, 'archive'])->middleware(EnsureAdminAccess::class)->name('admin.news.archive');
Route::delete('/admin/content/news/{id}', [AdminNewsController::class, 'destroy'])->middleware(EnsureAdminAccess::class)->name('admin.news.destroy');
Route::get('/admin/content/participants', [AdminParticipantsController::class, 'index'])->middleware(EnsureAdminAccess::class)->name('admin.participants.index');
Route::get('/admin/content/participants/new', [AdminParticipantsController::class, 'create'])->middleware(EnsureAdminAccess::class)->name('admin.participants.create');
Route::post('/admin/content/participants', [AdminParticipantsController::class, 'store'])->middleware(EnsureAdminAccess::class)->name('admin.participants.store');
Route::get('/admin/content/participants/{id}', [AdminParticipantsController::class, 'edit'])->middleware(EnsureAdminAccess::class)->name('admin.participants.edit');
Route::put('/admin/content/participants/{id}', [AdminParticipantsController::class, 'update'])->middleware(EnsureAdminAccess::class)->name('admin.participants.update');
Route::post('/admin/content/participants/{id}/profile', [AdminParticipantsController::class, 'updateProfile'])->middleware(EnsureAdminAccess::class)->name('admin.participants.profile');
Route::post('/admin/content/participants/{id}/toggle', [AdminParticipantsController::class, 'toggle'])->middleware(EnsureAdminAccess::class)->name('admin.participants.toggle');
Route::delete('/admin/content/participants/{id}', [AdminParticipantsController::class, 'destroy'])->middleware(EnsureAdminAccess::class)->name('admin.participants.destroy');
Route::get('/admin/content/sponsors', [AdminSponsorsController::class, 'index'])->middleware(EnsureAdminAccess::class)->name('admin.sponsors.index');
Route::get('/admin/content/sponsors/new', [AdminSponsorsController::class, 'create'])->middleware(EnsureAdminAccess::class)->name('admin.sponsors.create');
Route::post('/admin/content/sponsors', [AdminSponsorsController::class, 'store'])->middleware(EnsureAdminAccess::class)->name('admin.sponsors.store');
Route::get('/admin/content/sponsors/{id}', [AdminSponsorsController::class, 'edit'])->middleware(EnsureAdminAccess::class)->name('admin.sponsors.edit');
Route::put('/admin/content/sponsors/{id}', [AdminSponsorsController::class, 'update'])->middleware(EnsureAdminAccess::class)->name('admin.sponsors.update');
Route::post('/admin/content/sponsors/{id}/toggle', [AdminSponsorsController::class, 'toggle'])->middleware(EnsureAdminAccess::class)->name('admin.sponsors.toggle');
Route::delete('/admin/content/sponsors/{id}', [AdminSponsorsController::class, 'destroy'])->middleware(EnsureAdminAccess::class)->name('admin.sponsors.destroy');
Route::get('/admin/content/events', [AdminEventsController::class, 'index'])->middleware(EnsureAdminAccess::class)->name('admin.events.index');
Route::get('/admin/content/events/new', [AdminEventsController::class, 'create'])->middleware(EnsureAdminAccess::class)->name('admin.events.create');
Route::post('/admin/content/events', [AdminEventsController::class, 'store'])->middleware(EnsureAdminAccess::class)->name('admin.events.store');
Route::get('/admin/content/events/{id}', [AdminEventsController::class, 'edit'])->middleware(EnsureAdminAccess::class)->name('admin.events.edit');
Route::put('/admin/content/events/{id}', [AdminEventsController::class, 'update'])->middleware(EnsureAdminAccess::class)->name('admin.events.update');
Route::post('/admin/content/events/reorder', [AdminEventsController::class, 'reorder'])->middleware(EnsureAdminAccess::class)->name('admin.events.reorder');
Route::delete('/admin/content/events/{id}', [AdminEventsController::class, 'destroy'])->middleware(EnsureAdminAccess::class)->name('admin.events.destroy');
Route::get('/admin/content/galleries', [AdminGalleriesController::class, 'index'])->middleware(EnsureAdminAccess::class)->name('admin.galleries.index');
Route::get('/admin/content/galleries/new', [AdminGalleriesController::class, 'create'])->middleware(EnsureAdminAccess::class)->name('admin.galleries.create');
Route::post('/admin/content/galleries', [AdminGalleriesController::class, 'store'])->middleware(EnsureAdminAccess::class)->name('admin.galleries.store');
Route::get('/admin/content/galleries/{id}', [AdminGalleriesController::class, 'edit'])->middleware(EnsureAdminAccess::class)->name('admin.galleries.edit');
Route::put('/admin/content/galleries/{id}', [AdminGalleriesController::class, 'update'])->middleware(EnsureAdminAccess::class)->name('admin.galleries.update');
Route::post('/admin/content/galleries/{id}/items', [AdminGalleriesController::class, 'addItems'])->middleware(EnsureAdminAccess::class)->name('admin.galleries.items.add');
Route::put('/admin/content/galleries/{galleryId}/items/{itemId}', [AdminGalleriesController::class, 'updateItem'])->middleware(EnsureAdminAccess::class)->name('admin.galleries.items.update');
Route::delete('/admin/content/galleries/{galleryId}/items/{itemId}', [AdminGalleriesController::class, 'deleteItem'])->middleware(EnsureAdminAccess::class)->name('admin.galleries.items.delete');
Route::post('/admin/content/galleries/{id}/items/reorder', [AdminGalleriesController::class, 'reorderItems'])->middleware(EnsureAdminAccess::class)->name('admin.galleries.items.reorder');
Route::delete('/admin/content/galleries/{id}', [AdminGalleriesController::class, 'destroy'])->middleware(EnsureAdminAccess::class)->name('admin.galleries.destroy');
Route::get('/admin', AdminDashboardController::class)->middleware(EnsureAdminAccess::class)->name('admin.dashboard');
Route::get('/monitor', [PublicPageController::class, 'monitor'])->middleware(EnsureAdminAccess::class)->name('admin.monitor');

Route::get('/tentang', [PublicPageController::class, 'about'])->name('public.about');
Route::get('/berita/{slug}', [PublicPageController::class, 'news'])
    ->where('slug', '[a-z0-9]+(?:-[a-z0-9]+)*')
    ->name('public.news.show');
Route::get('/rangkaian-kegiatan/{event}', [PublicPageController::class, 'event'])->name('public.events.show');
Route::get('/profil-finalis/{category}/{name}', [PublicPageController::class, 'finalist'])->name('public.finalists.show');
Route::get('/profil-finalis/{category}', [PublicPageController::class, 'finalists'])->name('public.finalists.index');
Route::get('/profil-semifinalis/{category}/{name}', [PublicPageController::class, 'semifinalist'])->name('public.semifinalists.show');
Route::get('/profil-semifinalis/{category}', [PublicPageController::class, 'semifinalists'])->name('public.semifinalists.index');
Route::get('/voting/hasil/{category}', [PublicPageController::class, 'votingResults'])->name('public.voting.results');
Route::get('/voting/{category}/{name}', [PublicPageController::class, 'votingCandidate'])->name('public.voting.show');
Route::get('/voting/{category}', [PublicPageController::class, 'voting'])->name('public.voting.index');
