<?php

use App\Http\Controllers\AdminAuditController;
use App\Http\Controllers\AdminCommitteeController;
use App\Http\Controllers\AdminContentController;
use App\Http\Controllers\AdminDashboardController;
use App\Http\Controllers\AdminEditionContextController;
use App\Http\Controllers\AdminEditionController;
use App\Http\Controllers\AdminEditionSettingsController;
use App\Http\Controllers\AdminEventsController;
use App\Http\Controllers\AdminGalleriesController;
use App\Http\Controllers\AdminMediaController;
use App\Http\Controllers\AdminNewsController;
use App\Http\Controllers\AdminOrganizationController;
use App\Http\Controllers\AdminParticipantsController;
use App\Http\Controllers\AdminProfileController;
use App\Http\Controllers\AdminRequestAccessController;
use App\Http\Controllers\AdminSelectionController;
use App\Http\Controllers\AdminSiteAssetsController;
use App\Http\Controllers\AdminSponsorsController;
use App\Http\Controllers\AdminUsersController;
use App\Http\Controllers\AdminVotingController;
use App\Http\Controllers\Auth\GoogleAuthenticationController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PublicPageController;
use App\Http\Controllers\UploadThingController;
use App\Http\Middleware\EnsureAdminAccess;
use Illuminate\Support\Facades\Route;

Route::get('/', HomeController::class)->name('home');

Route::get('/api/uploadthing', [UploadThingController::class, 'metadata'])->name('uploadthing.endpoint');
Route::post('/api/uploadthing', [UploadThingController::class, 'handle'])->name('uploadthing.action');

Route::get('/admin/login', [GoogleAuthenticationController::class, 'showLogin'])->name('admin.login');
Route::get('/auth/google/redirect', [GoogleAuthenticationController::class, 'redirectToGoogle'])->name('auth.google.redirect');
Route::get('/auth/google/callback', [GoogleAuthenticationController::class, 'handleGoogleCallback'])->name('auth.google.callback');
Route::post('/logout', [GoogleAuthenticationController::class, 'logout'])->middleware('auth')->name('logout');
Route::get('/admin/request-access', AdminRequestAccessController::class)->middleware('auth')->name('admin.request-access');
Route::post('/admin/request-access', [AdminRequestAccessController::class, 'store'])->middleware('auth')->name('admin.request-access.store');
Route::get('/admin/profile', AdminProfileController::class)->middleware('auth')->name('admin.profile');
Route::post('/admin/context/edition', [AdminEditionContextController::class, 'store'])->middleware(EnsureAdminAccess::class)->name('admin.edition-context.store');
Route::get('/admin/users', [AdminUsersController::class, 'index'])->middleware(EnsureAdminAccess::class)->name('admin.users');
Route::post('/admin/users/access-requests/{accessRequest}/approve', [AdminUsersController::class, 'approve'])->middleware(EnsureAdminAccess::class)->name('admin.access-requests.approve');
Route::get('/admin/audit', AdminAuditController::class)->middleware(EnsureAdminAccess::class)->name('admin.audit');
Route::get('/admin/content', [AdminContentController::class, 'index'])->middleware(EnsureAdminAccess::class)->name('admin.content.index');
Route::get('/admin/content/pages', fn () => redirect()->route('admin.site-assets.index'))->middleware(EnsureAdminAccess::class)->name('admin.content.pages');
Route::get('/admin/content/people', fn () => redirect()->route('admin.organization.index'))->middleware(EnsureAdminAccess::class)->name('admin.content.people');
Route::get('/admin/content/editions', [AdminEditionController::class, 'index'])->middleware(EnsureAdminAccess::class)->name('admin.editions.index');
Route::post('/admin/content/editions', [AdminEditionController::class, 'store'])->middleware(EnsureAdminAccess::class)->name('admin.editions.store');
Route::post('/admin/content/editions/categories', [AdminEditionController::class, 'storeCategory'])->middleware(EnsureAdminAccess::class)->name('admin.editions.categories.store');
Route::post('/admin/content/editions/{id}/activate', [AdminEditionController::class, 'activate'])->middleware(EnsureAdminAccess::class)->name('admin.editions.activate');
Route::get('/admin/content/edition-settings', [AdminEditionSettingsController::class, 'index'])->middleware(EnsureAdminAccess::class)->name('admin.edition-settings.index');
Route::put('/admin/content/edition-settings', [AdminEditionSettingsController::class, 'update'])->middleware(EnsureAdminAccess::class)->name('admin.edition-settings.update');
Route::post('/admin/content/edition-settings/programs', [AdminEditionSettingsController::class, 'storeProgram'])->middleware(EnsureAdminAccess::class)->name('admin.edition-settings.programs.store');
Route::put('/admin/content/edition-settings/programs/{id}', [AdminEditionSettingsController::class, 'updateProgram'])->middleware(EnsureAdminAccess::class)->name('admin.edition-settings.programs.update');
Route::post('/admin/content/edition-settings/programs/reorder', [AdminEditionSettingsController::class, 'reorderPrograms'])->middleware(EnsureAdminAccess::class)->name('admin.edition-settings.programs.reorder');
Route::delete('/admin/content/edition-settings/programs/{id}', [AdminEditionSettingsController::class, 'destroyProgram'])->middleware(EnsureAdminAccess::class)->name('admin.edition-settings.programs.destroy');
Route::get('/admin/content/site-assets', [AdminSiteAssetsController::class, 'index'])->middleware(EnsureAdminAccess::class)->name('admin.site-assets.index');
Route::post('/admin/content/site-assets/{slotKey}', [AdminSiteAssetsController::class, 'bind'])->middleware(EnsureAdminAccess::class)->name('admin.site-assets.bind');
Route::delete('/admin/content/site-assets/{slotKey}', [AdminSiteAssetsController::class, 'unbind'])->middleware(EnsureAdminAccess::class)->name('admin.site-assets.unbind');
Route::get('/admin/media', [AdminMediaController::class, 'index'])->middleware(EnsureAdminAccess::class)->name('admin.media.index');
Route::post('/admin/media/folders', [AdminMediaController::class, 'storeFolder'])->middleware(EnsureAdminAccess::class)->name('admin.media.folders.store');
Route::put('/admin/media/folders/{id}', [AdminMediaController::class, 'updateFolder'])->middleware(EnsureAdminAccess::class)->name('admin.media.folders.update');
Route::put('/admin/media/assets/{id}', [AdminMediaController::class, 'updateAssetMetadata'])->middleware(EnsureAdminAccess::class)->name('admin.media.assets.update');
Route::put('/admin/media/assets/{id}/move', [AdminMediaController::class, 'moveAsset'])->middleware(EnsureAdminAccess::class)->name('admin.media.assets.move');
Route::get('/admin/voting', [AdminVotingController::class, 'index'])->middleware(EnsureAdminAccess::class)->name('admin.voting.index');
Route::post('/admin/voting/campaigns', [AdminVotingController::class, 'storeCampaign'])->middleware(EnsureAdminAccess::class)->name('admin.voting.campaigns.store');
Route::put('/admin/voting/campaigns/{id}/stage', [AdminVotingController::class, 'updateCampaignStage'])->middleware(EnsureAdminAccess::class)->name('admin.voting.campaigns.stage');
Route::post('/admin/voting/campaigns/{id}/start', [AdminVotingController::class, 'startCampaign'])->middleware(EnsureAdminAccess::class)->name('admin.voting.campaigns.start');
Route::post('/admin/voting/campaigns/{id}/close', [AdminVotingController::class, 'closeCampaign'])->middleware(EnsureAdminAccess::class)->name('admin.voting.campaigns.close');
Route::post('/admin/voting/campaigns/{id}/visibility', [AdminVotingController::class, 'updateVisibility'])->middleware(EnsureAdminAccess::class)->name('admin.voting.campaigns.visibility');
Route::post('/admin/voting/tallies', [AdminVotingController::class, 'storeTally'])->middleware(EnsureAdminAccess::class)->name('admin.voting.tallies.store');
Route::get('/admin/content/news', [AdminNewsController::class, 'index'])->middleware(EnsureAdminAccess::class)->name('admin.news.index');
Route::get('/admin/content/news/new', [AdminNewsController::class, 'create'])->middleware(EnsureAdminAccess::class)->name('admin.news.create');
Route::post('/admin/content/news', [AdminNewsController::class, 'store'])->middleware(EnsureAdminAccess::class)->name('admin.news.store');
Route::get('/admin/content/news/{id}', [AdminNewsController::class, 'edit'])->middleware(EnsureAdminAccess::class)->name('admin.news.edit');
Route::put('/admin/content/news/{id}', [AdminNewsController::class, 'update'])->middleware(EnsureAdminAccess::class)->name('admin.news.update');
Route::post('/admin/content/news/{id}/publish', [AdminNewsController::class, 'publish'])->middleware(EnsureAdminAccess::class)->name('admin.news.publish');
Route::post('/admin/content/news/{id}/unpublish', [AdminNewsController::class, 'unpublish'])->middleware(EnsureAdminAccess::class)->name('admin.news.unpublish');
Route::post('/admin/content/news/{id}/archive', [AdminNewsController::class, 'archive'])->middleware(EnsureAdminAccess::class)->name('admin.news.archive');
Route::delete('/admin/content/news/{id}', [AdminNewsController::class, 'destroy'])->middleware(EnsureAdminAccess::class)->name('admin.news.destroy');
Route::get('/admin/content/participants', [AdminParticipantsController::class, 'index'])->middleware(EnsureAdminAccess::class)->name('admin.participants.index');
Route::get('/admin/content/participants/new', [AdminParticipantsController::class, 'create'])->middleware(EnsureAdminAccess::class)->name('admin.participants.create');
Route::post('/admin/content/participants', [AdminParticipantsController::class, 'store'])->middleware(EnsureAdminAccess::class)->name('admin.participants.store');
Route::get('/admin/content/participants/stages', [AdminSelectionController::class, 'stagesIndex'])->middleware(EnsureAdminAccess::class)->name('admin.selection.stages.index');
Route::post('/admin/content/participants/stages', [AdminSelectionController::class, 'storeStage'])->middleware(EnsureAdminAccess::class)->name('admin.selection.stages.store');
Route::post('/admin/content/participants/stages/reorder', [AdminSelectionController::class, 'reorderStages'])->middleware(EnsureAdminAccess::class)->name('admin.selection.stages.reorder');
Route::get('/admin/content/participants/stages/{id}', [AdminSelectionController::class, 'stageWorkspace'])->middleware(EnsureAdminAccess::class)->name('admin.selection.stage.workspace');
Route::put('/admin/content/participants/stages/{id}', [AdminSelectionController::class, 'updateStage'])->middleware(EnsureAdminAccess::class)->name('admin.selection.stage.update');
Route::post('/admin/content/participants/stages/{id}/open', [AdminSelectionController::class, 'openStage'])->middleware(EnsureAdminAccess::class)->name('admin.selection.stage.open');
Route::post('/admin/content/participants/stages/{id}/decisions', [AdminSelectionController::class, 'setStageDecisions'])->middleware(EnsureAdminAccess::class)->name('admin.selection.stage.decisions');
Route::post('/admin/content/participants/stages/{stageId}/entries/{entryId}/rollback', [AdminSelectionController::class, 'rollbackDecision'])->middleware(EnsureAdminAccess::class)->name('admin.selection.stage.rollback');
Route::post('/admin/content/participants/stages/{id}/close', [AdminSelectionController::class, 'closeStage'])->middleware(EnsureAdminAccess::class)->name('admin.selection.stage.close');
Route::post('/admin/content/participants/stages/{id}/reopen', [AdminSelectionController::class, 'reopenStage'])->middleware(EnsureAdminAccess::class)->name('admin.selection.stage.reopen');
Route::delete('/admin/content/participants/stages/{id}', [AdminSelectionController::class, 'destroyStage'])->middleware(EnsureAdminAccess::class)->name('admin.selection.stage.destroy');
Route::get('/admin/content/participants/titles', [AdminSelectionController::class, 'titlesIndex'])->middleware(EnsureAdminAccess::class)->name('admin.selection.titles.index');
Route::post('/admin/content/participants/titles', [AdminSelectionController::class, 'storeTitle'])->middleware(EnsureAdminAccess::class)->name('admin.selection.titles.store');
Route::post('/admin/content/participants/titles/reorder', [AdminSelectionController::class, 'reorderTitles'])->middleware(EnsureAdminAccess::class)->name('admin.selection.titles.reorder');
Route::put('/admin/content/participants/titles/{id}', [AdminSelectionController::class, 'updateTitle'])->middleware(EnsureAdminAccess::class)->name('admin.selection.title.update');
Route::post('/admin/content/participants/titles/{id}/toggle', [AdminSelectionController::class, 'toggleTitle'])->middleware(EnsureAdminAccess::class)->name('admin.selection.title.toggle');
Route::delete('/admin/content/participants/titles/{id}', [AdminSelectionController::class, 'destroyTitle'])->middleware(EnsureAdminAccess::class)->name('admin.selection.title.destroy');
Route::post('/admin/content/participants/titles/{id}/assign', [AdminSelectionController::class, 'assignTitle'])->middleware(EnsureAdminAccess::class)->name('admin.selection.title.assign');
Route::post('/admin/content/participants/titles/{id}/unassign', [AdminSelectionController::class, 'unassignTitle'])->middleware(EnsureAdminAccess::class)->name('admin.selection.title.unassign');
Route::get('/admin/content/participants/{id}', [AdminParticipantsController::class, 'edit'])->middleware(EnsureAdminAccess::class)->name('admin.participants.edit');
Route::put('/admin/content/participants/{id}', [AdminParticipantsController::class, 'update'])->middleware(EnsureAdminAccess::class)->name('admin.participants.update');
Route::post('/admin/content/participants/{id}/profile', [AdminParticipantsController::class, 'updateProfile'])->middleware(EnsureAdminAccess::class)->name('admin.participants.profile');
Route::post('/admin/content/participants/{id}/toggle', [AdminParticipantsController::class, 'toggle'])->middleware(EnsureAdminAccess::class)->name('admin.participants.toggle');
Route::delete('/admin/content/participants/{id}', [AdminParticipantsController::class, 'destroy'])->middleware(EnsureAdminAccess::class)->name('admin.participants.destroy');
Route::get('/admin/organization', [AdminOrganizationController::class, 'index'])->middleware(EnsureAdminAccess::class)->name('admin.organization.index');
Route::get('/admin/organization/periods/{id}', [AdminOrganizationController::class, 'show'])->middleware(EnsureAdminAccess::class)->name('admin.organization.periods.show');
Route::post('/admin/organization/periods', [AdminOrganizationController::class, 'storePeriod'])->middleware(EnsureAdminAccess::class)->name('admin.organization.periods.store');
Route::put('/admin/organization/periods/{id}', [AdminOrganizationController::class, 'updatePeriod'])->middleware(EnsureAdminAccess::class)->name('admin.organization.periods.update');
Route::post('/admin/organization/periods/{id}/editions', [AdminOrganizationController::class, 'setPeriodEditions'])->middleware(EnsureAdminAccess::class)->name('admin.organization.periods.editions');
Route::delete('/admin/organization/periods/{id}', [AdminOrganizationController::class, 'destroyPeriod'])->middleware(EnsureAdminAccess::class)->name('admin.organization.periods.destroy');
Route::post('/admin/organization/units', [AdminOrganizationController::class, 'storeUnit'])->middleware(EnsureAdminAccess::class)->name('admin.organization.units.store');
Route::put('/admin/organization/units/{id}', [AdminOrganizationController::class, 'updateUnit'])->middleware(EnsureAdminAccess::class)->name('admin.organization.units.update');
Route::post('/admin/organization/units/reorder', [AdminOrganizationController::class, 'reorderUnits'])->middleware(EnsureAdminAccess::class)->name('admin.organization.units.reorder');
Route::delete('/admin/organization/units/{id}', [AdminOrganizationController::class, 'destroyUnit'])->middleware(EnsureAdminAccess::class)->name('admin.organization.units.destroy');
Route::post('/admin/organization/memberships', [AdminOrganizationController::class, 'storeMembership'])->middleware(EnsureAdminAccess::class)->name('admin.organization.memberships.store');
Route::put('/admin/organization/memberships/{id}', [AdminOrganizationController::class, 'updateMembership'])->middleware(EnsureAdminAccess::class)->name('admin.organization.memberships.update');
Route::delete('/admin/organization/memberships/{id}', [AdminOrganizationController::class, 'destroyMembership'])->middleware(EnsureAdminAccess::class)->name('admin.organization.memberships.destroy');
Route::post('/admin/organization/people', [AdminOrganizationController::class, 'storePerson'])->middleware(EnsureAdminAccess::class)->name('admin.organization.people.store');
Route::put('/admin/organization/people/{id}', [AdminOrganizationController::class, 'updatePerson'])->middleware(EnsureAdminAccess::class)->name('admin.organization.people.update');
Route::delete('/admin/organization/people/{id}', [AdminOrganizationController::class, 'destroyPerson'])->middleware(EnsureAdminAccess::class)->name('admin.organization.people.destroy');
Route::post('/admin/organization/legacy/map', [AdminOrganizationController::class, 'mapLegacy'])->middleware(EnsureAdminAccess::class)->name('admin.organization.legacy.map');
Route::get('/admin/content/committee', [AdminCommitteeController::class, 'index'])->middleware(EnsureAdminAccess::class)->name('admin.committee.index');
Route::post('/admin/content/committee/units', [AdminCommitteeController::class, 'storeUnit'])->middleware(EnsureAdminAccess::class)->name('admin.committee.units.store');
Route::put('/admin/content/committee/units/{id}', [AdminCommitteeController::class, 'updateUnit'])->middleware(EnsureAdminAccess::class)->name('admin.committee.units.update');
Route::post('/admin/content/committee/units/reorder', [AdminCommitteeController::class, 'reorderUnits'])->middleware(EnsureAdminAccess::class)->name('admin.committee.units.reorder');
Route::delete('/admin/content/committee/units/{id}', [AdminCommitteeController::class, 'destroyUnit'])->middleware(EnsureAdminAccess::class)->name('admin.committee.units.destroy');
Route::post('/admin/content/committee/assignments', [AdminCommitteeController::class, 'storeAssignment'])->middleware(EnsureAdminAccess::class)->name('admin.committee.assignments.store');
Route::put('/admin/content/committee/assignments/{id}', [AdminCommitteeController::class, 'updateAssignment'])->middleware(EnsureAdminAccess::class)->name('admin.committee.assignments.update');
Route::delete('/admin/content/committee/assignments/{id}', [AdminCommitteeController::class, 'destroyAssignment'])->middleware(EnsureAdminAccess::class)->name('admin.committee.assignments.destroy');
Route::post('/admin/content/committee/people', [AdminCommitteeController::class, 'storeQuickPerson'])->middleware(EnsureAdminAccess::class)->name('admin.committee.people.store');
Route::get('/admin/content/sponsors', [AdminSponsorsController::class, 'index'])->middleware(EnsureAdminAccess::class)->name('admin.sponsors.index');
Route::get('/admin/content/sponsors/new', [AdminSponsorsController::class, 'create'])->middleware(EnsureAdminAccess::class)->name('admin.sponsors.create');
Route::post('/admin/content/sponsors', [AdminSponsorsController::class, 'store'])->middleware(EnsureAdminAccess::class)->name('admin.sponsors.store');
Route::get('/admin/content/sponsors/{id}', [AdminSponsorsController::class, 'edit'])->middleware(EnsureAdminAccess::class)->name('admin.sponsors.edit');
Route::put('/admin/content/sponsors/{id}', [AdminSponsorsController::class, 'update'])->middleware(EnsureAdminAccess::class)->name('admin.sponsors.update');
Route::post('/admin/content/sponsors/{id}/toggle', [AdminSponsorsController::class, 'toggle'])->middleware(EnsureAdminAccess::class)->name('admin.sponsors.toggle');
Route::delete('/admin/content/sponsors/{id}', [AdminSponsorsController::class, 'destroy'])->middleware(EnsureAdminAccess::class)->name('admin.sponsors.destroy');
Route::get('/admin/content/events', [AdminEventsController::class, 'index'])->middleware(EnsureAdminAccess::class)->name('admin.events.index');
Route::get('/admin/content/events/new', [AdminEventsController::class, 'create'])->middleware(EnsureAdminAccess::class)->name('admin.events.create');
Route::post('/admin/content/events', [AdminEventsController::class, 'store'])->middleware(EnsureAdminAccess::class)->name('admin.events.store');
Route::get('/admin/content/events/{id}', [AdminEventsController::class, 'edit'])->middleware(EnsureAdminAccess::class)->name('admin.events.edit');
Route::put('/admin/content/events/{id}', [AdminEventsController::class, 'update'])->middleware(EnsureAdminAccess::class)->name('admin.events.update');
Route::post('/admin/content/events/reorder', [AdminEventsController::class, 'reorder'])->middleware(EnsureAdminAccess::class)->name('admin.events.reorder');
Route::delete('/admin/content/events/{id}', [AdminEventsController::class, 'destroy'])->middleware(EnsureAdminAccess::class)->name('admin.events.destroy');
Route::get('/admin/content/galleries', [AdminGalleriesController::class, 'index'])->middleware(EnsureAdminAccess::class)->name('admin.galleries.index');
Route::get('/admin/content/galleries/new', [AdminGalleriesController::class, 'create'])->middleware(EnsureAdminAccess::class)->name('admin.galleries.create');
Route::post('/admin/content/galleries', [AdminGalleriesController::class, 'store'])->middleware(EnsureAdminAccess::class)->name('admin.galleries.store');
Route::get('/admin/content/galleries/{id}', [AdminGalleriesController::class, 'edit'])->middleware(EnsureAdminAccess::class)->name('admin.galleries.edit');
Route::put('/admin/content/galleries/{id}', [AdminGalleriesController::class, 'update'])->middleware(EnsureAdminAccess::class)->name('admin.galleries.update');
Route::post('/admin/content/galleries/{id}/items', [AdminGalleriesController::class, 'addItems'])->middleware(EnsureAdminAccess::class)->name('admin.galleries.items.add');
Route::put('/admin/content/galleries/{galleryId}/items/{itemId}', [AdminGalleriesController::class, 'updateItem'])->middleware(EnsureAdminAccess::class)->name('admin.galleries.items.update');
Route::delete('/admin/content/galleries/{galleryId}/items/{itemId}', [AdminGalleriesController::class, 'deleteItem'])->middleware(EnsureAdminAccess::class)->name('admin.galleries.items.delete');
Route::post('/admin/content/galleries/{id}/items/reorder', [AdminGalleriesController::class, 'reorderItems'])->middleware(EnsureAdminAccess::class)->name('admin.galleries.items.reorder');
Route::delete('/admin/content/galleries/{id}', [AdminGalleriesController::class, 'destroy'])->middleware(EnsureAdminAccess::class)->name('admin.galleries.destroy');
Route::get('/admin', AdminDashboardController::class)->middleware(EnsureAdminAccess::class)->name('admin.dashboard');
Route::get('/monitor', [PublicPageController::class, 'monitor'])->middleware(EnsureAdminAccess::class)->name('admin.monitor');

Route::get('/z_contact___', [PublicPageController::class, 'legacyContact'])->name('legacy.contact');
Route::get('/z_pasanggiri__', [PublicPageController::class, 'legacyPasanggiri'])->name('legacy.pasanggiri');
Route::get('/z_pasanggiri__/voting/{name}', [PublicPageController::class, 'legacyVoting'])->name('legacy.voting.show');

Route::get('/tentang', [PublicPageController::class, 'about'])->name('public.about');
Route::get('/berita/{slug}', [PublicPageController::class, 'news'])
    ->where('slug', '[a-z0-9]+(?:-[a-z0-9]+)*')
    ->name('public.news.show');
Route::get('/rangkaian-kegiatan/{event}', [PublicPageController::class, 'event'])->name('public.events.show');
Route::get('/profil-finalis/{category}/{name}', [PublicPageController::class, 'finalist'])->name('public.finalists.show');
Route::get('/profil-finalis/{category}', [PublicPageController::class, 'finalists'])->name('public.finalists.index');
Route::get('/profil-semifinalis/{category}/{name}', [PublicPageController::class, 'semifinalist'])->name('public.semifinalists.show');
Route::get('/profil-semifinalis/{category}', [PublicPageController::class, 'semifinalists'])->name('public.semifinalists.index');
Route::get('/voting/hasil/{category}', [PublicPageController::class, 'votingResults'])->name('public.voting.results');
Route::get('/voting/{category}/{name}', [PublicPageController::class, 'votingCandidate'])->name('public.voting.show');
Route::get('/voting/{category}', [PublicPageController::class, 'voting'])->name('public.voting.index');
