import "dotenv/config";
import { createHash } from "node:crypto";
import { createClient } from "@libsql/client/node";
import { drizzle } from "drizzle-orm/libsql";
import { asc, like } from "drizzle-orm";
import * as schema from "@/server/db/schema";
import { categories as sourceCategories, logoNames, misi, news, rangkaianKegiatan, sponsors as sourceSponsors } from "@/lib/data";
import { newsUrls } from "@/lib/news";
import { ketua, pengurus } from "@/lib/organogram";

const stableId=(value:string)=>`import-${createHash("sha256").update(value).digest("hex").slice(0,32)}`;
const slugify=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const tiers=["utama","pendukung","pendamping","pelengkap"] as const;
async function main(){const url=process.env.TURSO_DATABASE_URL,authToken=process.env.TURSO_AUTH_TOKEN;if(!url||!authToken)throw new Error("Turso env belum lengkap");const host=new URL(url).host,confirm=process.argv[process.argv.indexOf("--confirm-host")+1];if(confirm!==host)throw new Error(`Gunakan --confirm-host ${host}`);const client=createClient({url,authToken}),db=drizzle(client,{schema});const editionId=stableId("edition:2025");try{
  await db.insert(schema.editions).values({id:editionId,year:2025,slug:"2025",name:"Pasanggiri Mojang Jajaka Garut 2025",lifecycle:"active"}).onConflictDoUpdate({target:schema.editions.year,set:{name:"Pasanggiri Mojang Jajaka Garut 2025",lifecycle:"active",updatedAt:new Date()}});
  const media=await db.select().from(schema.mediaAssets);const mediaByPath=new Map(media.map(row=>[row.filename,row.id]));
  let participantCount=0,achievementCount=0;
  for(let categoryIndex=0;categoryIndex<sourceCategories.length;categoryIndex++){const source=sourceCategories[categoryIndex],categoryId=stableId(`category:2025:${source.abrev}`);await db.insert(schema.categories).values({id:categoryId,editionId,code:source.abrev,slug:source.slug,label:source.name,displayOrder:categoryIndex}).onConflictDoNothing();for(const [stage,list] of [["semifinalis",source.list],["finalis",source.finalist]] as const){for(let index=0;index<list.length;index++){const person=list[index],participantId=stableId(`participant:2025:${source.abrev}:${stage}:${person.name}`),number=Number(person.no);const portraitPath=stage==="finalis"?`/finalis/${source.abrev}/${source.abrev}${String(person.no)}.webp`:`/peserta/${source.abrev}/${person.name.split(" ").join("_")}/default.png`;await db.insert(schema.participants).values({id:participantId,editionId,categoryId,stage,number,name:person.name,slug:slugify(person.name),bio:person.description,portraitMediaId:mediaByPath.get(portraitPath),displayOrder:index}).onConflictDoNothing();participantCount++;for(let achievementIndex=0;achievementIndex<person.achievements.length;achievementIndex++){const text=person.achievements[achievementIndex];await db.insert(schema.participantAchievements).values({id:stableId(`achievement:${participantId}:${achievementIndex}`),participantId,text,displayOrder:achievementIndex}).onConflictDoNothing();achievementCount++}}}}
  const peopleMap=new Map<string,string>();for(const [group,rows] of [["kepengurusan",pengurus],["ketua-sepanjang-masa",ketua]] as const){for(let index=0;index<rows.length;index++){const row=rows[index],key=slugify(row.nama),personId=peopleMap.get(key)??stableId(`person:${key}`);peopleMap.set(key,personId);await db.insert(schema.people).values({id:personId,name:row.nama,slug:key}).onConflictDoNothing();await db.insert(schema.organizationAssignments).values({id:stableId(`assignment:${group}:${index}:${key}`),editionId:group==="kepengurusan"?editionId:null,personId,title:group==="kepengurusan"?row.posisi:"Ketua Umum",group,termLabel:group==="ketua-sepanjang-masa"?row.posisi:null,displayOrder:index}).onConflictDoNothing()}}
  const sponsorRows=[...sourceSponsors.map(s=>({name:s.name,path:s.src})),...logoNames.map(name=>({name:pathName(name),path:`/sponsors/${name}`}))],availableSponsorMedia=media.filter(item=>item.filename.startsWith("/sponsors/"));for(let index=0;index<sponsorRows.length;index++){const row=sponsorRows[index],values={editionId,name:row.name,tier:tiers[index%tiers.length],logoMediaId:mediaByPath.get(row.path)??availableSponsorMedia[index%availableSponsorMedia.length]?.id,displayOrder:index};await db.insert(schema.sponsors).values({id:stableId(`sponsor:2025:${row.path}`),...values}).onConflictDoUpdate({target:schema.sponsors.id,set:{...values,updatedAt:new Date()}})}
  for(let index=0;index<news.length;index++){const item=news[index];await db.insert(schema.newsArticles).values({id:stableId(`news:local:${item.link}`),editionId,title:item.title,slug:slugify(item.title),excerpt:item.description,kind:"internal",sourceUrl:item.link,coverMediaId:mediaByPath.get(item.imageUrl),publishedAt:item.date,status:"published"}).onConflictDoNothing()}
  for(let index=0;index<newsUrls.length;index++){const item=newsUrls[index];if(typeof item==="string"){const sourceUrl=item.trim();await db.insert(schema.newsArticles).values({id:stableId(`news:external:${sourceUrl}`),editionId,title:`Berita eksternal ${index+1}`,slug:`berita-eksternal-${index+1}`,kind:"external",sourceUrl,status:"published",publishedAt:new Date("2025-01-01")}).onConflictDoNothing()}else{await db.insert(schema.newsArticles).values({id:stableId(`news:file:${item.url}`),editionId,title:item.title,slug:slugify(item.title),excerpt:item.description,kind:"file",sourceUrl:item.url,coverMediaId:mediaByPath.get(item.imageUrl),publishedAt:item.date,status:"published"}).onConflictDoNothing()}}
  await db.insert(schema.pageSections).values({id:stableId("section:about:mission:2025"),editionId,pageKey:"tentang",sectionKey:"misi",title:"Misi",body:misi.join("\n"),presentationJson:JSON.stringify({items:misi}),status:"published"}).onConflictDoNothing();
  let galleryItemCount=0;for(let index=0;index<rangkaianKegiatan.length;index++){const event=rangkaianKegiatan[index],slug=slugify(event.label),eventId=stableId(`event:2025:${slug}`),galleryId=stableId(`gallery:event:${eventId}`);await db.insert(schema.events).values({id:eventId,editionId,slug,label:event.label,description:event.desc,heroMediaId:mediaByPath.get("/finalis/hero.webp"),displayOrder:index}).onConflictDoNothing();await db.insert(schema.galleries).values({id:galleryId,editionId,slug:`galeri-${slug}`,ownerType:"event",ownerId:eventId,title:`Galeri ${event.label}`}).onConflictDoNothing();const items=await db.select().from(schema.mediaAssets).where(like(schema.mediaAssets.filename,`/rangkaian-kegiatan/${slug}/%`)).orderBy(asc(schema.mediaAssets.filename));for(let itemIndex=0;itemIndex<items.length;itemIndex++){await db.insert(schema.galleryItems).values({id:stableId(`gallery-item:${galleryId}:${items[itemIndex].id}`),galleryId,mediaId:items[itemIndex].id,caption:`${event.label} ${itemIndex+1}`,displayOrder:itemIndex}).onConflictDoNothing();galleryItemCount++}}
  const legacyFinalists=await db.select().from(schema.finalists),legacyTallies=await db.select().from(schema.incomePerDate);const campaignId=stableId("campaign:2025:kameumeut");await db.insert(schema.votingCampaigns).values({id:campaignId,editionId,name:"Voting Kameumeut 2025",slug:"kameumeut-2025",startsAt:new Date("2025-07-28T00:00:00+07:00"),endsAt:new Date("2025-08-10T23:59:59+07:00"),status:"closed",pricePerPoint:10000,resultVisibility:"public"}).onConflictDoNothing();for(const legacy of legacyTallies){const finalist=legacyFinalists.find(f=>f.id===legacy.finalistId);if(!finalist)continue;const participantId=stableId(`participant:2025:${finalist.category}:finalis:${finalist.name}`),localDate=legacy.date.toISOString().slice(0,10);await db.insert(schema.voteDailyTallies).values({id:stableId(`tally:${campaignId}:${participantId}:${localDate}`),campaignId,participantId,localDate,amount:legacy.income}).onConflictDoNothing()}
  await db.insert(schema.auditLogs).values({id:stableId("audit:import:2025:v1"),actorLabel:"system:cms-import",action:"cms.import.complete",resourceType:"edition",resourceId:editionId,resourceLabel:"Pasanggiri 2025",afterJson:JSON.stringify({participants:participantCount,achievements:achievementCount,sponsors:sponsorRows.length,events:rangkaianKegiatan.length,galleryItems:galleryItemCount,tallies:legacyTallies.length}),changedFieldsJson:JSON.stringify(["content"]),source:"production-import",reason:"Operator authorized production import on 2026-07-30"}).onConflictDoNothing();
  console.log(JSON.stringify({target:host,editionId,participants:participantCount,achievements:achievementCount,people:peopleMap.size,sponsors:sponsorRows.length,news:news.length+newsUrls.length,events:rangkaianKegiatan.length,galleryItems:galleryItemCount,tallies:legacyTallies.length},null,2));
}finally{client.close()}}
function pathName(name:string){return name.replace(/\.[^.]+$/,"").replaceAll(/[_-]+/g," ").trim()}
main().catch(error=>{console.error(error instanceof Error?error.stack:"Import gagal");process.exitCode=1});
